#配置详解https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8
#密码加密https://github.com/alibaba/druid/wiki/%E4%BD%BF%E7%94%A8ConfigFilter
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    #加密的密码,原始值是空串""
    password: YdwoSUF2sC3V18JArpFojeLHzKO7WIZePmPI5KpvWcz37VtgqSnTzWldcjQ8UdLXAJr/d5Q6UVCSKy5KGoF5WQ==
    driverClassName: com.mysql.jdbc.Driver
    #密码公钥
    public.key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKuMFryYhnHAuA5p1TgEIOT9q3jTKCM5B2/ydvyAzRS+0YYruKRG6/HUPhDopmqrYqEi74kFO8kMThb7fG6mAb8CAwEAAQ==
    #stat=StatFilter,用于sql监控,wall=WallFilter,防止sql注入,config用于密码加密
    filters: stat,wall,slf4j,config
    #配置初始化大小、最小、最大 
    initialSize: 5
    minIdle: 5
    maxActive: 20
    #配置获取连接等待超时的时间
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #合并sql;慢sql为时间超过5000ms;指定密码解密;密码公钥
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=${spring.datasource.public.key}
